language: node_js
node_js:
  - node
cache: 
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - yarn add global bolt

install: bolt
script: yarn test