title: okmarvin
description: static site generator with better theme developer experience
author: Sam Chen
url: https://okmarvin.com
toc: true
theme: '@okmarvin/january'
menu:
  - text: Home
    permalink: /
  - text: About
    permalink: /about
github: chenxsan