title = "okmarvin"
description = "Static site generator with component as template."
author = "Sam Chen"
# base url
url = "https://okmarvin.com"
# generate table of contents
toc = true
# default theme
theme = "@okmarvin/january"

rss = false
paginate = 20
# favicon = "/static/img/favicon.png"
# logo = "/static/img/logo.svg"

[[menu]]
text = "Home"
permalink = "/"

[[menu]]
text = "About"
permalink = "/about/"