// json schema for okmarvin
module.exports = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'Site',
  description: 'Data for static site generated by okmarvin',
  type: 'object',
  required: ['root', 'dest', 'builtAt', 'okmarvinConfig', 'site', 'files'],
  properties: {
    root: {
      description: 'Project root',
      type: 'string'
    },
    dest: {
      description: 'Where to output our site',
      type: 'string'
    },
    builtAt: {
      description:
        'When site building begins, could be used as date for index pages',
      type: 'integer'
    },
    okmarvinConfig: {
      description: 'Customized configuration for okmarvin',
      type: 'object',
      properties: {}
    },
    site: {
      description: 'Site-wide configuration',
      type: 'object',
      properties: {
        title: {
          description: 'Site name',
          type: 'string'
        },
        description: {
          description: 'Site tagline',
          type: 'string'
        },
        url: {
          description: 'Site url after deployed',
          type: 'string',
          format: 'uri'
        },
        author: {
          description: 'Default author',
          type: 'string'
        },
        lang: {
          description: 'language code',
          type: 'string'
        },
        theme: {
          description: 'theme for okmarvin',
          type: 'string'
        },
        themeColor: {
          description: 'theme color',
          type: 'string'
        },
        toc: {
          description: 'enable/disable toc',
          type: 'boolean'
        },
        permalink: {
          description: 'permalink pattern',
          type: 'string'
        },
        rss: {
          description: 'Generate RSS or not',
          type: 'boolean'
        },
        favicon: {
          description: 'favicon',
          type: 'string',
          pattern: '.(gif|png|ico)$'
        },
        logo: {
          description: 'Site logo',
          type: 'string'
        },
        paginate: {
          description: 'Maximum posts in one page',
          type: 'integer'
        },
        github: {
          description: 'Github username',
          type: 'string'
        },
        twitter: {
          description: 'Twitter username',
          type: 'string'
        },
        google_analytics: {
          description: 'Google Analytics ID',
          type: 'string'
        },
        layoutHierarchy: {
          description: 'Layouts hierarchy',
          type: 'object',
          properties: {
            'index.js': {
              type: 'array',
              items: {
                type: 'string'
              }
            },
            'post.js': {
              type: 'array',
              items: {
                type: 'string'
              }
            },
            'page.js': {
              type: 'array',
              items: {
                type: 'string'
              }
            },
            'tag.js': {
              type: 'array',
              items: {
                type: 'string'
              }
            },
            'category.js': {
              type: 'array',
              items: {
                type: 'string'
              }
            },
            '404.js': {
              type: 'array',
              items: {
                type: 'string'
              }
            }
          }
        }
      },
      menu: {
        description: 'Site menu',
        type: 'array',
        items: {
          type: 'object',
          properties: {
            text: {
              description: 'menu text',
              type: 'string'
            },
            permalink: {
              description: 'menu permalink',
              type: 'string',
              pattern: '^/[^.]*(.html|.htm|/)??$'
            }
          }
        },
        required: ['text', 'permalink']
      }
    },
    files: {
      description: 'file array',
      type: 'array',
      uniqueItems: true,
      items: {
        description: 'file data',
        type: 'object',
        properties: {
          title: {
            description: 'article title',
            type: 'string'
          },
          author: {
            description: 'article author',
            type: 'string'
          },
          excerpt: {
            description: 'article excerpt',
            type: 'string'
          },
          date: {
            description: 'Date when article published',
            type: ['string', 'object']
          },
          dateModified: {
            description: 'Date when article modified',
            type: ['string', 'object']
          },
          permalink: {
            description: 'Article permalink',
            type: 'string',
            pattern: '^/(?!static/)' // do not begin with preserved `/static/`
          },
          template: {
            description: 'Article template',
            type: 'string',
            pattern: '.js$'
          },
          layout: {
            description: 'Article layout',
            type: 'string'
          },
          toc: {
            description: 'enable/disable toc',
            type: 'boolean'
          },
          tags: {
            type: 'array',
            items: {
              type: 'string'
            }
          },
          categories: {
            type: 'array',
            items: {
              type: 'string'
            }
          }
        }
      }
    }
  }
}
