'use strict'

const fs = require('fs-extra')
const path = require('path')

/**
 * In okmarvin, file composed of site config, file data,
 * file template, file layout, client js, and file css
 * data is generated by markdown-it, so we need to take it into account too
 * for incremental rebuild, we need to figure all of theme out
 */

const defaultCache = {
  themeManifest: {}, // medium frequency
  clientJsManifest: {}, // medium frequency
  files: [], // high frequency
  layoutHash: [], // low frequency
  okmarvinConfig: {}, // low frequency
  siteConfig: {} // low frequency
}

module.exports = ({ root }, callback) => {
  // Cache for incremental rebuild
  try {
    const data = fs.readJsonSync(path.join(root, '_cache.json'))
    callback(null, {
      ...defaultCache,
      ...data
    })
  } catch (err) {
    return callback(null, defaultCache)
  }
}
