title: okmarvin
description: Static site generator with better theme developer experience.
author: Sam Chen
url: https://okmarvin.com
toc: true
theme: '@okmarvin/january'
menu:
  - text: Home
    permalink: /
  - text: About
    permalink: /about
rss: false
paginate: 20
favicon: /static/img/favicon.png
logo: /static/img/logo.svg